# Generated by Django 3.2.7 on 2023-01-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230128_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='country',
        ),
        migrations.RemoveField(
            model_name='service',
            name='state',
        ),
        migrations.RemoveField(
            model_name='service',
            name='zipcode',
        ),
    ]
