# Generated by Django 3.2.7 on 2023-01-30 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230128_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('processing', 'processing'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='processing', max_length=100)),
                ('duration', models.CharField(choices=[('3_days', '3 Days'), ('1_week', '1 week'), ('less_a_month', 'Less than a month'), ('1_to_3_months', '1 to 3 Months')], default='3_days', max_length=100)),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='api.service')),
            ],
            options={
                'verbose_name_plural': '4. Orders',
                'ordering': ['date'],
            },
        ),
    ]
